# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CloudImageClipboard' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CloudImageClipboard

  pod 'ProjectRomeSdk'

  target 'CloudImageClipboardTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CloudImageClipboardUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
